# Ecllipse Field Bug Classifier

In [3]:
## Importing some basic required libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [4]:
ef_data1 = pd.read_csv("D:\External_Projects\Kaushiki_Mishra\Data and Code\EclipseFields.csv")

In [5]:
ef_data1

BugID  MasterID  MergeID            Product  Component         Type  \
0      214049         0        0         z_Archived        STP       normal   
1      224159         0        0         z_Archived     Cosmos       normal   
2      224160         0        0           Platform       Text       normal   
3      224161         0        0         z_Archived     Cosmos       normal   
4      224162         0        0  Target Management        RSE        major   
...       ...       ...      ...                ...        ...          ...   
45229  224157         0        0         z_Archived     Cosmos       normal   
45230  224158         0        0                JDT       Text       normal   
45231  215057         0        0              Mylyn      Tasks  enhancement   
45232  214148         0        0                PDE         UI  enhancement   
45233  214058         0   108534           Platform  Resources       normal   

      Priority  PriorityNumber      Version  VersionNumber  ...  \
0           P3             3.0  unspecified            0.0  ...   
1           P3             3.0  unspecified            0.0  ...   
2           P3             3.0          3.4            0.0  ...   
3           P3             3.0  unspecified            0.0  ...   
4           P2             2.0  unspecified            0.0  ...   
...        ...             ...          ...            ...  ...   
45229       P3             3.0  unspecified            0.0  ...   
45230       P3             3.0        3.3.1            0.0  ...   
45231       P3             3.0  unspecified            0.0  ...   
45232       P3             3.0          3.4            0.0  ...   
45233       P3             3.0          3.3            0.0  ...   

                           CloseDate     Status Stars    crypto   general  \
0      Fri Sep 21 22:10:55 IRST 2012      FIXED     0   4.82183   5.38393   
1      Tue Jan 03 22:18:21 IRST 2012      FIXED     0   3.50751   5.10120   
2      Tue May 13 14:57:07 IRDT 2008        NaN     0   5.67471   6.51821   
3      Tue Jan 03 22:17:09 IRST 2012      FIXED     0  12.18324  16.71032   
4      Wed Apr 02 22:05:41 IRDT 2008      FIXED     0  10.08601  13.12250   
...                              ...        ...   ...       ...       ...   
45229  Tue Jan 03 22:17:39 IRST 2012      FIXED     0   4.21042   7.68664   
45230  Fri Mar 28 14:13:27 IRDT 2008      FIXED     0   4.37787   5.85958   
45231  Wed Nov 05 06:01:27 IRST 2008      FIXED     0   5.41726  10.69461   
45232  Tue Feb 05 23:20:17 IRST 2008      FIXED     0   0.00000   8.18088   
45233  Mon Jan 07 15:26:11 IRST 2008  DUPLICATE     0   8.47968   9.65786   

           java  networking  \
0       5.38393     5.38393   
1       3.50751     3.50751   
2       6.51821     5.13549   
3      15.29347    12.18324   
4      11.81216    11.47312   
...         ...         ...   
45229   6.28164     6.28164   
45230   5.85958     5.85958   
45231   7.39037     9.53942   
45232   1.91619     0.70898   
45233   9.65786     8.47968   

                                                   Title  \
0      produce tutorial content for policy editor for...   
1      graph response viewer: table columns can not b...   
2       [templates view] editor drop target has problems   
3      graph response viewer: improve the format of t...   
4      systemeditableremotefile.saveas does not work ...   
...                                                  ...   
45229  graph response viewer: need to better decode u...   
45230  [syntax highlighting] class is not colored whe...   
45231  [api] add support for pre and post task deacti...   
45232                      remove the classpath: setting   
45233  files which are copied while building workspac...   

                                             Description Summary  
0      eclipsecon 2007 has a tutorial on policy edito...     NaN  
1      table columns shown in the graph response view...     NaN  
2      i20080327-0100.  the editor

In [6]:
ef_data1.shape

(45234, 21)

In [7]:
ef_data1.isna().sum()

BugID                 0
MasterID              0
MergeID               0
Product               0
Component             0
Type                  0
Priority              0
PriorityNumber        0
Version               0
VersionNumber         0
OpenDate              0
CloseDate             0
Status             6797
Stars                 0
crypto                0
general               0
java                  0
networking            0
Title                 0
Description           2
Summary           45234
dtype: int64

In [8]:
ef_data2 = ef_data1.drop(columns="Summary")

In [9]:
ef_data2.isnull().sum()

BugID                0
MasterID             0
MergeID              0
Product              0
Component            0
Type                 0
Priority             0
PriorityNumber       0
Version              0
VersionNumber        0
OpenDate             0
CloseDate            0
Status            6797
Stars                0
crypto               0
general              0
java                 0
networking           0
Title                0
Description          2
dtype: int64

In [10]:
ef_data3 = ef_data2.dropna()

In [11]:
ef_data3.isna().sum()

BugID             0
MasterID          0
MergeID           0
Product           0
Component         0
Type              0
Priority          0
PriorityNumber    0
Version           0
VersionNumber     0
OpenDate          0
CloseDate         0
Status            0
Stars             0
crypto            0
general           0
java              0
networking        0
Title             0
Description       0
dtype: int64

In [12]:
ef_data3["MasterID"].value_counts()

MasterID
0    38435
Name: count, dtype: int64

In [13]:
ef_data3["MergeID"].value_counts()

MergeID
0         34094
214092       33
240753       29
248683       20
236513       19
          ...  
234591        1
221969        1
196308        1
237109        1
108534        1
Name: count, Length: 3382, dtype: int64

In [14]:
ef_data3["Stars"].value_counts()

Stars
0    38435
Name: count, dtype: int64

In [15]:
ef_data3["VersionNumber"].value_counts()

VersionNumber
0.0    38435
Name: count, dtype: int64

In [16]:
ef_data3["Version"].value_counts()

Version
unspecified    11363
3.4             7141
3.0             2284
2.3.0           2210
3.5             1825
               ...  
2.0 M2             1
0.6                1
4.4                1
3.6.2              1
1.1.1              1
Name: count, Length: 167, dtype: int64

In [17]:
ef_data4 = ef_data3.drop(columns=["BugID","MasterID","MergeID","OpenDate","CloseDate","Stars","VersionNumber"])

In [18]:
ef_data4

Product   Component         Type Priority  PriorityNumber  \
0             z_Archived         STP       normal       P3             3.0   
1             z_Archived      Cosmos       normal       P3             3.0   
3             z_Archived      Cosmos       normal       P3             3.0   
4      Target Management         RSE        major       P2             2.0   
5            EclipseLink  Foundation       normal       P3             3.0   
...                  ...         ...          ...      ...             ...   
45229         z_Archived      Cosmos       normal       P3             3.0   
45230                JDT        Text       normal       P3             3.0   
45231              Mylyn       Tasks  enhancement       P3             3.0   
45232                PDE          UI  enhancement       P3             3.0   
45233           Platform   Resources       normal       P3             3.0   

           Version     Status    crypto   general      java  networking  \
0      unspecified      FIXED   4.82183   5.38393   5.38393     5.38393   
1      unspecified      FIXED   3.50751   5.10120   3.50751     3.50751   
3      unspecified      FIXED  12.18324  16.71032  15.29347    12.18324   
4      unspecified      FIXED  10.08601  13.12250  11.81216    11.47312   
5              1.0      FIXED   0.00000   0.00000   0.00000     0.00000   
...            ...        ...       ...       ...       ...         ...   
45229  unspecified      FIXED   4.21042   7.68664   6.28164     6.28164   
45230        3.3.1      FIXED   4.37787   5.85958   5.85958     5.85958   
45231  unspecified      FIXED   5.41726  10.69461   7.39037     9.53942   
45232          3.4      FIXED   0.00000   8.18088   1.91619     0.70898   
45233          3.3  DUPLICATE   8.47968   9.65786   9.65786     8.47968   

                                                   Title  \
0      produce tutorial content for policy editor for...   
1      graph response viewer: table columns can not b...   
3      graph response viewer: improve the format of t...   
4      systemeditableremotefile.saveas does not work ...   
5             build needs to generate jars per component   
...                                                  ...   
45229  graph response viewer: need to better decode u...   
45230  [syntax highlighting] class is not colored whe...   
45231  [api] add support for pre and post task deacti...   
45232                      remove the classpath: setting   
45233  files which are copied while building workspac...   

                                             Description  
0      eclipsecon 2007 has a tutorial on policy edito...  
1      table columns shown in the graph response view...  
3      should format the xml structure of the record ...  
4      created attachment 93648 plugin with junit tha...  
5              these are the precursors to osgi bundles.  
...                                                  ...  
45229  when a url is shown in the graph response view...  
45230  created attachment 93646 screenshot of cot col...  
45231  it would be nice to have support for pre- and ...  
45232  since the dawn of jarred plug-ins  setting the...  
45233  build id: i20070625-1500  steps to reproduce: ...  

[38435 rows x 13 columns]

In [19]:
ef_data5 = ef_data4.reset_index(drop=True)

In [20]:
ef_data5["Status"].value_counts()

Status
FIXED          27019
DUPLICATE       4341
WONTFIX         2343
WORKSFORME      2107
INVALID         1938
NOT_ECLIPSE      687
Name: count, dtype: int64

In [21]:
ef_data5["Status"] = [-1 if bug_type == "INVALID" else 1 for bug_type in ef_data5["Status"]]

In [22]:
ef_data5["Status"].value_counts()   ## Data is highly imbalance

Status
 1    36497
-1     1938
Name: count, dtype: int64

In [23]:
X = ef_data5.drop(columns = "Status")  ## Our input features for futher analysis

In [24]:
X

Product   Component         Type Priority  PriorityNumber  \
0             z_Archived         STP       normal       P3             3.0   
1             z_Archived      Cosmos       normal       P3             3.0   
2             z_Archived      Cosmos       normal       P3             3.0   
3      Target Management         RSE        major       P2             2.0   
4            EclipseLink  Foundation       normal       P3             3.0   
...                  ...         ...          ...      ...             ...   
38430         z_Archived      Cosmos       normal       P3             3.0   
38431                JDT        Text       normal       P3             3.0   
38432              Mylyn       Tasks  enhancement       P3             3.0   
38433                PDE          UI  enhancement       P3             3.0   
38434           Platform   Resources       normal       P3             3.0   

           Version    crypto   general      java  networking  \
0      unspecified   4.82183   5.38393   5.38393     5.38393   
1      unspecified   3.50751   5.10120   3.50751     3.50751   
2      unspecified  12.18324  16.71032  15.29347    12.18324   
3      unspecified  10.08601  13.12250  11.81216    11.47312   
4              1.0   0.00000   0.00000   0.00000     0.00000   
...            ...       ...       ...       ...         ...   
38430  unspecified   4.21042   7.68664   6.28164     6.28164   
38431        3.3.1   4.37787   5.85958   5.85958     5.85958   
38432  unspecified   5.41726  10.69461   7.39037     9.53942   
38433          3.4   0.00000   8.18088   1.91619     0.70898   
38434          3.3   8.47968   9.65786   9.65786     8.47968   

                                                   Title  \
0      produce tutorial content for policy editor for...   
1      graph response viewer: table columns can not b...   
2      graph response viewer: improve the format of t...   
3      systemeditableremotefile.saveas does not work ...   
4             build needs to generate jars per component   
...                                                  ...   
38430  graph response viewer: need to better decode u...   
38431  [syntax highlighting] class is not colored whe...   
38432  [api] add support for pre and post task deacti...   
38433                      remove the classpath: setting   
38434  files which are copied while building workspac...   

                                             Description  
0      eclipsecon 2007 has a tutorial on policy edito...  
1      table columns shown in the graph response view...  
2      should format the xml structure of the record ...  
3      created attachment 93648 plugin with junit tha...  
4              these are the precursors to osgi bundles.  
...                                                  ...  
38430  when a url is shown in the graph response view...  
38431  created attachment 93646 screenshot of cot col...  
38432  it would be nice to have support for pre- and ...  
38433  since the dawn of jarred plug-ins  setting the...  
38434  build id: i20070625-1500  steps to reproduce: ...  

[38435 rows x 12 columns]

In [25]:
Bug_details = []
for i in range(len(X)):
  Bug_detail = ' '.join(str(detail) for detail in X.iloc[i,0:12])
  Bug_details.append(Bug_detail)

In [26]:
Bug_details[3]

'Target Management RSE major P2 2.0 unspecified 10.08601 13.1225 11.81216 11.47312 systemeditableremotefile.saveas does not work because fileservicesubsytem.upload does invalid check created attachment 93648 plugin with junit that demonstrates the error  build id: i20080207-1530  steps to reproduce: 1. detach the project that has been included with this bug 2. right click on class saveaserror and run a junit plug-in test 3. when prompted  select any *.txt file on your local machine (this testcase will attempt to save the *.txt file to the name *.txt.saveastest in the same folder as the selected object) 4. press ok 5. you will then see an error appear (rseg8002). 6. press ok. testcase fails  and the file was not saved to the new name.  more information: the save as operation fails for editors that implement isystemtexteditor and use systemeditableremotefile.saveas method. the reason for this seems to be that the fileservicesubsystem.upload method that gets eventually called does the fol

In [27]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [28]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\amanv\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


True

In [29]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\amanv\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [30]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\amanv\AppData\Roaming\nltk_data...


True

In [31]:
Lemmatizer = WordNetLemmatizer()

In [32]:
bug_details_cleaned = []

for i in range(len(Bug_details)):
    bug_detail = Bug_details[i]
    bug_detail = re.sub(r'\(\d{1,2}/\d{1,2}/\d{4} \d{1,2}:\d{1,2}:\d{1,2} [APMapm]{2}\);', '', bug_detail)
    bug_detail_words = nltk.word_tokenize(bug_detail)
    bug_detail_words = [Lemmatizer.lemmatize(word) for word in bug_detail_words if word not in set(stopwords.words('english'))]
    bug_detail = ' '.join(bug_detail_words)
    bug_detail = bug_detail.lower()
    bug_details_cleaned.append(bug_detail)

In [33]:
bug_details_cleaned[2]

'z_archived cosmos normal p3 3.0 unspecified 12.18324 16.71032 15.29347 12.18324 graph response viewer : improve format xml format xml structure record content . format happen demand . user expands node call javascript function format xml string store formatted string back store .'

In [34]:
word_count = [len(bug_detail) for bug_detail in bug_details_cleaned]

In [35]:
ef_des_df = pd.DataFrame({
                            "Description" : bug_details_cleaned,
                            "Description_length" : word_count


})

In [36]:
ef_des_df

Description  Description_length
0      z_archived stp normal p3 3.0 unspecified 4.821...                 282
1      z_archived cosmos normal p3 3.0 unspecified 3....                 168
2      z_archived cosmos normal p3 3.0 unspecified 12...                 280
3      target management rse major p2 2.0 unspecified...                1020
4      eclipselink foundation normal p3 3.0 1.0 0.0 0...                 118
...                                                  ...                 ...
38430  z_archived cosmos normal p3 3.0 unspecified 4....                 233
38431  jdt text normal p3 3.0 3.3.1 4.37787 5.85958 5...                 406
38432  mylyn tasks enhancement p3 3.0 unspecified 5.4...                 473
38433  pde ui enhancement p3 3.0 3.4 0.0 8.18088 1.91...                 259
38434  platform resources normal p3 3.0 3.3 8.47968 9...                 673

[38435 rows x 2 columns]

In [37]:
ef_des_df["Description_length"].describe()

count    38435.000000
mean      1012.210329
std       2445.653323
min         57.000000
25%        283.000000
50%        438.000000
75%        766.000000
max      72777.000000
Name: Description_length, dtype: float64

In [39]:
import tensorflow as tf

In [40]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [41]:
voc_size = 10000
one_hot_representation = [one_hot(news,voc_size) for news in bug_details_cleaned]

In [42]:
sentence_length = 1113
embedded_doc = pad_sequences(one_hot_representation,padding='pre',maxlen=sentence_length)
print(embedded_doc)

[[   0    0    0 ... 6244 2240 5249]
 [   0    0    0 ... 3028 3930 7027]
 [   0    0    0 ... 4529 9281 4357]
 ...
 [   0    0    0 ... 9622 2562 1656]
 [   0    0    0 ... 1911 1410 5952]
 [   0    0    0 ... 2751 8693 2331]]


In [43]:
X = np.array(embedded_doc)
y = np.array(ef_data5["Status"])

In [45]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=42)

## Support Vector Classifier

In [48]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [44]:
svm_model = SVC(kernel='rbf')
svm_model.fit(X_train, y_train)

SVC()

In [45]:
predictions_rbf = svm_model.predict(X_test)


In [46]:
accuracy = accuracy_score(y_test, predictions_rbf)
precision = precision_score(y_test, predictions_rbf)
recall = recall_score(y_test, predictions_rbf)
f1 = f1_score(y_test, predictions_rbf)


In [47]:

print(f"Accuracy: {accuracy * 100:.2f}%")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")

Accuracy: 94.86%
Precision: 0.95
Recall: 1.00
F1 Score: 0.97


## Linear Discriminant Analysis

In [85]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [86]:
lda_model = LinearDiscriminantAnalysis()

In [87]:
lda_model.fit(X_train, y_train)

LinearDiscriminantAnalysis()

In [88]:
predictions_lda = lda_model.predict(X_test)

In [89]:
accuracy = accuracy_score(y_test, predictions_lda)
precision = precision_score(y_test, predictions_lda)
recall = recall_score(y_test, predictions_lda)
f1 = f1_score(y_test, predictions_lda)

In [90]:
print(f"Accuracy: {accuracy * 100:.2f}%")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")

Accuracy: 93.31%
Precision: 0.95
Recall: 0.98
F1 Score: 0.97


## KNN

In [49]:
from sklearn.neighbors import KNeighborsClassifier

knn_classifier = KNeighborsClassifier(n_neighbors=5)
knn_classifier.fit(X_train, y_train)
knn_pred = knn_classifier.predict(X_test)

accuracy = accuracy_score(y_test, knn_pred)
precision = precision_score(y_test, knn_pred)
recall = recall_score(y_test, knn_pred)
f1 = f1_score(y_test, knn_pred)

print(f"Accuracy: {accuracy * 100:.2f}%")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")



Accuracy: 94.87%
Precision: 0.95
Recall: 1.00
F1 Score: 0.97


## Naive Bayes

In [51]:
from sklearn.naive_bayes import MultinomialNB
nb_classifier = MultinomialNB()
nb_classifier.fit(X_train, y_train)
nb_pred = nb_classifier.predict(X_test)

accuracy = accuracy_score(y_test, nb_pred)
precision = precision_score(y_test, nb_pred)
recall = recall_score(y_test, nb_pred)
f1 = f1_score(y_test, nb_pred)

print(f"Accuracy: {accuracy * 100:.2f}%")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")



Accuracy: 39.65%
Precision: 0.96
Recall: 0.38
F1 Score: 0.55


## XG-Boost Classifier

In [55]:
y_train_mapped = np.where(y_train == -1, 0, y_train)
y_test_mapped = np.where(y_test == -1, 0, y_test)
xgb_classifier = xgb.XGBClassifier()
xgb_classifier.fit(X_train, y_train_mapped)
xgb_pred = xgb_classifier.predict(X_test)

accuracy = accuracy_score(y_test_mapped, xgb_pred)
precision = precision_score(y_test_mapped, xgb_pred)
recall = recall_score(y_test_mapped, xgb_pred)
f1 = f1_score(y_test_mapped, xgb_pred)

print(f"Accuracy: {accuracy * 100:.2f}%")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")


Accuracy: 94.95%
Precision: 0.95
Recall: 1.00
F1 Score: 0.97
