# Mozilla Field Bug Classifier

In [11]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [1]:
## Importing some basic required libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
mf_data1 = pd.read_csv("C:/Users/Vedant Vidhate/Desktop/Data and Code/MozillaFields.csv", encoding='ISO-8859-1')

In [3]:
mf_data1

BugID  MasterID   MergeID           Product            Component  \
0      537438       0.0       0.0  Fennec Graveyard              General   
1      548566       0.0       0.0       mozilla.org    Server Operations   
2      548567       0.0  548531.0           Plugins        Flash (Adobe)   
3      548568       0.0  397937.0           Firefox  Phishing Protection   
4      548569       0.0       0.0       mozilla.org    Discussion Forums   
...       ...       ...       ...               ...                  ...   
75693  548564       0.0       0.0              Core        Widget: Cocoa   
75694  548565       0.0       0.0       mozilla.org  Release Engineering   
75695  538545       0.0       0.0           Tamarin      Virtual Machine   
75696  537539       0.0       0.0       mozilla.org  Release Engineering   
75697  537447       0.0  536296.0  Fennec Graveyard              General   

           Type Priority  PriorityNumber      Version  VersionNumber  ...  \
0        normal       --             0.0        Trunk            0.0  ...   
1         major       --             0.0        other            0.0  ...   
2      critical       --             0.0         10.x            0.0  ...   
3        normal       --             0.0  unspecified            0.0  ...   
4        normal       --             0.0        other            0.0  ...   
...         ...      ...             ...          ...            ...  ...   
75693  critical       --             0.0  unspecified            0.0  ...   
75694    normal       P5             5.0        other            0.0  ...   
75695    normal       --             0.0  unspecified            0.0  ...   
75696  critical       --             0.0        other            0.0  ...   
75697     minor       --             0.0        Trunk            0.0  ...   

                           CloseDate     Status Stars    crypto   general  \
0      Mon Aug 22 20:00:40 IRDT 2011        NaN   0.0   9.36379  15.06490   
1      Wed Mar 10 21:38:39 IRST 2010    WONTFIX   0.0  11.89965  15.53109   
2      Fri Apr 23 17:13:24 IRDT 2010  DUPLICATE   0.0   2.71370   4.43300   
3      Thu Feb 25 22:10:43 IRST 2010  DUPLICATE   0.0   8.78630  11.16785   
4      Wed Apr 21 13:25:55 IRDT 2010    INVALID   0.0   4.97225   5.30194   
...                              ...        ...   ...       ...       ...   
75693  Mon Dec 12 17:59:13 IRST 2011        NaN   0.0   3.65607   5.58688   
75694  Fri Feb 26 02:27:54 IRST 2010    WONTFIX   0.0   3.30156   5.95881   
75695  Thu Sep 23 21:03:13 IRST 2010      FIXED   0.0   1.34831   3.87113   
75696  Thu Jan 07 01:21:34 IRST 2010      FIXED   0.0   4.38087   4.08487   
75697  Tue Jun 29 02:39:53 IRDT 2010  DUPLICATE   0.0   5.20424   8.25413   

           java  networking  \
0      12.12623    11.40087   
1      12.08567    14.32417   
2       3.87280     3.66773   
3       9.01698     9.74638   
4       4.16117     4.97225   
...         ...         ...   
75693   5.26590     5.18477   
75694   2.93718     3.77433   
75695   3.02868     3.02150   
75696   2.94534     2.59930   
75697   5.86056     9.29996   

                                                   Title  \
0      mouse pointer hover mode  similar to maemo's d...   
1                           clean up breakpad nfs store.   
2                               [oopp] adobe flash crash   
3       web forgery message break the view source window   
4      migrate "mozilla.community.drumbeat" group to ...   
...                                                  ...   
75693                    crash [@ _class_isinitialized ]   
75694                      create 15 new linux 64 slaves   
75695  zeroing of strings table in avmcore::avmcore p...   
75696  localized builds are not updating since decemb...   
75697  common web fonts eg. tahoma or rendered as ser...   

                                             Description Summary  
0      maemo's default browser  also based on firefox...     NaN  
1      we are run

In [4]:
mf_data1.shape

(75698, 21)

In [5]:
mf_data1.isna().sum()

BugID                 0
MasterID             58
MergeID              58
Product              75
Component            75
Type                 75
Priority             75
PriorityNumber       58
Version              75
VersionNumber        58
OpenDate             58
CloseDate            58
Status            13452
Stars                58
crypto               58
general              58
java                 58
networking           58
Title                75
Description          78
Summary           75698
dtype: int64

In [6]:
mf_data2 = mf_data1.drop(columns="Summary")

In [7]:
mf_data2["Status"].value_counts()

Status
FIXED         33456
DUPLICATE     10478
WORKSFORME     6007
INVALID        4551
INCOMPLETE     4221
WONTFIX        3530
MOVED             2
EXPIRED           1
Name: count, dtype: int64

In [8]:
mf_data3 = mf_data2.dropna()

In [9]:
mf_data4 = mf_data3.reset_index(drop=True)

In [10]:
mf_data4

BugID  MasterID   MergeID           Product  \
0      548566       0.0       0.0       mozilla.org   
1      548567       0.0  548531.0           Plugins   
2      548568       0.0  397937.0           Firefox   
3      548569       0.0       0.0       mozilla.org   
4      548570       0.0       0.0           Tamarin   
...       ...       ...       ...               ...   
62238  548563       0.0       0.0       mozilla.org   
62239  548565       0.0       0.0       mozilla.org   
62240  538545       0.0       0.0           Tamarin   
62241  537539       0.0       0.0       mozilla.org   
62242  537447       0.0  536296.0  Fennec Graveyard   

                       Component      Type Priority  PriorityNumber  \
0              Server Operations     major       --             0.0   
1                  Flash (Adobe)  critical       --             0.0   
2            Phishing Protection    normal       --             0.0   
3              Discussion Forums    normal       --             0.0   
4      Garbage Collection (mmGC)    normal       P3             3.0   
...                          ...       ...      ...             ...   
62238          Server Operations     major       --             0.0   
62239        Release Engineering    normal       P5             5.0   
62240            Virtual Machine    normal       --             0.0   
62241        Release Engineering  critical       --             0.0   
62242                    General     minor       --             0.0   

           Version  VersionNumber                       OpenDate  \
0            other            0.0  Thu Feb 25 18:58:00 IRST 2010   
1             10.x            0.0  Thu Feb 25 19:12:00 IRST 2010   
2      unspecified            0.0  Thu Feb 25 19:24:00 IRST 2010   
3            other            0.0  Thu Feb 25 19:29:00 IRST 2010   
4      unspecified            0.0  Thu Feb 25 19:32:00 IRST 2010   
...            ...            ...                            ...   
62238        other            0.0  Thu Feb 25 18:46:00 IRST 2010   
62239        other            0.0  Thu Feb 25 18:49:00 IRST 2010   
62240  unspecified            0.0  Fri Jan 08 12:30:00 IRST 2010   
62241        other            0.0  Sat Jan 02 21:51:00 IRST 2010   
62242        Trunk            0.0  Fri Jan 01 17:36:00 IRST 2010   

                           CloseDate     Status  Stars    crypto   general  \
0      Wed Mar 10 21:38:39 IRST 2010    WONTFIX    0.0  11.89965  15.53109   
1      Fri Apr 23 17:13:24 IRDT 2010  DUPLICATE    0.0   2.71370   4.43300   
2      Thu Feb 25 22:10:43 IRST 2010  DUPLICATE    0.0   8.78630  11.16785   
3      Wed Apr 21 13:25:55 IRDT 2010    INVALID    0.0   4.97225   5.30194   
4      Fri Apr 02 21:50:46 IRDT 2010      FIXED    0.0   2.91422   7.33212   
...                              ...        ...    ...       ...       ...   
62238  Thu Mar 04 00:22:40 IRST 2010      FIXED    0.0   2.91444   2.91444   
62239  Fri Feb 26 02:27:54 IRST 2010    WONTFIX    0.0   3.30156   5.95881   
62240  Thu Sep 23 21:03:13 IRST 2010      FIXED    0.0   1.34831   3.87113   
62241  Thu Jan 07 01:21:34 IRST 2010      FIXED    0.0   4.38087   4.08487   
62242  Tue Jun 29 02:39:53 IRDT 2010  DUPLICATE    0.0   5.20424   8.25413   

           java  networking  \
0      12.08567    14.32417   
1       3.87280     3.66773   
2       9.01698     9.74638   
3       4.16117     4.97225   
4       6.92064     8.08346   
...         ...         ...   
62238   2.91444     4.48528   
62239   2.93718     3.77433   
62240   3.02868     3.02150   
62241   2.94534     2.59930   
62242   5.86056     9.29996   

                                                   Title  \
0                           clean up breakpad nfs store.   
1                               [oopp] adobe flash crash   
2       web forgery message break the view source window   
3      migrate "mozilla.community.drumbeat" group to ...   
4      assertion failed: "((!m_startedfinalize))" ("/...   
...    

In [11]:
mf_data4["Status"].value_counts()

Status
FIXED         33455
DUPLICATE     10477
WORKSFORME     6007
INVALID        4551
INCOMPLETE     4220
WONTFIX        3530
MOVED             2
EXPIRED           1
Name: count, dtype: int64

In [12]:
mf_data4["Status"] = [-1 if bug_type == "INVALID" else 1 for bug_type in mf_data4["Status"]]

In [13]:
mf_data5 = mf_data4.drop(columns = ["BugID","MasterID","MergeID","OpenDate","CloseDate","Stars","VersionNumber"])

In [14]:
mf_data5

Product                  Component      Type Priority  \
0           mozilla.org          Server Operations     major       --   
1               Plugins              Flash (Adobe)  critical       --   
2               Firefox        Phishing Protection    normal       --   
3           mozilla.org          Discussion Forums    normal       --   
4               Tamarin  Garbage Collection (mmGC)    normal       P3   
...                 ...                        ...       ...      ...   
62238       mozilla.org          Server Operations     major       --   
62239       mozilla.org        Release Engineering    normal       P5   
62240           Tamarin            Virtual Machine    normal       --   
62241       mozilla.org        Release Engineering  critical       --   
62242  Fennec Graveyard                    General     minor       --   

       PriorityNumber      Version  Status    crypto   general      java  \
0                 0.0        other       1  11.89965  15.53109  12.08567   
1                 0.0         10.x       1   2.71370   4.43300   3.87280   
2                 0.0  unspecified       1   8.78630  11.16785   9.01698   
3                 0.0        other      -1   4.97225   5.30194   4.16117   
4                 3.0  unspecified       1   2.91422   7.33212   6.92064   
...               ...          ...     ...       ...       ...       ...   
62238             0.0        other       1   2.91444   2.91444   2.91444   
62239             5.0        other       1   3.30156   5.95881   2.93718   
62240             0.0  unspecified       1   1.34831   3.87113   3.02868   
62241             0.0        other       1   4.38087   4.08487   2.94534   
62242             0.0        Trunk       1   5.20424   8.25413   5.86056   

       networking                                              Title  \
0        14.32417                       clean up breakpad nfs store.   
1         3.66773                           [oopp] adobe flash crash   
2         9.74638   web forgery message break the view source window   
3         4.97225  migrate "mozilla.community.drumbeat" group to ...   
4         8.08346  assertion failed: "((!m_startedfinalize))" ("/...   
...           ...                                                ...   
62238     4.48528  point donate.mozilla.org and www.mozillians.or...   
62239     3.77433                      create 15 new linux 64 slaves   
62240     3.02150  zeroing of strings table in avmcore::avmcore p...   
62241     2.59930  localized builds are not updating since decemb...   
62242     9.29996  common web fonts eg. tahoma or rendered as ser...   

                                             Description  
0      we are running out of inode space on the nfs f...  
1      user-agent:       mozilla/5.0 (windows; u; win...  
2      when passing to a web forgery site which firef...  
3      please create a new group called "mozilla.drum...  
4      assertion fires in numerous test cases with de...  
...                                                  ...  
62238  please set up a records for donate.mozilla.org...  
62239  we will need these many machines to be able to...  
62240  the code is this:    strings = mmfx_new_array(...  
62241  mozilla/5.0 (x11; u; linux i686; fr; rv:1.9.3a...  
62242  user-agent:       mozilla/5.0 (windows; u; win...  

[62243 rows x 13 columns]

In [15]:
X = mf_data5.drop(columns = "Status")

In [16]:
Bug_details = []
for i in range(len(X)):
  Bug_detail = ' '.join(str(detail) for detail in X.iloc[i,0:12])
  Bug_details.append(Bug_detail)

In [17]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [18]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to C:\Users\Vedant
[nltk_data]     Vidhate\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [19]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Vedant
[nltk_data]     Vidhate\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [20]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to C:\Users\Vedant
[nltk_data]     Vidhate\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [21]:
Lemmatizer = WordNetLemmatizer()

In [22]:
bug_details_cleaned = []

for i in range(len(Bug_details)):
    bug_detail = Bug_details[i]
    bug_detail = re.sub(r'\(\d{1,2}/\d{1,2}/\d{4} \d{1,2}:\d{1,2}:\d{1,2} [APMapm]{2}\);', '', bug_detail)
    bug_detail_words = nltk.word_tokenize(bug_detail)
    bug_detail_words = [Lemmatizer.lemmatize(word) for word in bug_detail_words if word not in set(stopwords.words('english'))]
    bug_detail = ' '.join(bug_detail_words)
    bug_detail = bug_detail.lower()
    bug_details_cleaned.append(bug_detail)

In [23]:
word_count = [len(bug_detail) for bug_detail in bug_details_cleaned]

In [24]:
ep_des_df = pd.DataFrame({
                            "Description" : bug_details_cleaned,
                            "Description_length" : word_count


})

In [25]:
ep_des_df["Description_length"].describe()

count    62243.000000
mean       768.848481
std       1411.519183
min         64.000000
25%        310.000000
50%        511.000000
75%        830.000000
max      40837.000000
Name: Description_length, dtype: float64

In [26]:
import tensorflow as tf

In [27]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [28]:
voc_size = 10000
one_hot_representation = [one_hot(news,voc_size) for news in bug_details_cleaned]

In [29]:
sentence_length = 1500
embedded_doc = pad_sequences(one_hot_representation,padding='pre',maxlen=sentence_length)
print(embedded_doc)

[[   0    0    0 ... 7637 3390 3490]
 [   0    0    0 ... 6110  109 2347]
 [   0    0    0 ... 4429 3958 7310]
 ...
 [   0    0    0 ... 7623 6951 9413]
 [   0    0    0 ... 5533 8962 3770]
 [   0    0    0 ... 8619 9676 7563]]


In [30]:
X = np.array(embedded_doc)
y = np.array(mf_data5["Status"])

In [31]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=42)

# svc

In [32]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [33]:
svm_model = SVC(kernel='rbf')
svm_model.fit(X_train, y_train)

SVC()

In [34]:
predictions_rbf = svm_model.predict(X_test)


In [48]:
accuracy = accuracy_score(y_test, predictions_rbf)
precision = precision_score(y_test, predictions_rbf)
recall = recall_score(y_test, predictions_rbf)
f1 = f1_score(y_test, predictions_rbf)


In [49]:

print(f"Accuracy: {accuracy * 100:.2f}%")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")

Accuracy: 92.57%
Precision: 0.93
Recall: 1.00
F1 Score: 0.96


# LDA

In [50]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [53]:
lda_model = LinearDiscriminantAnalysis()

In [54]:
lda_model.fit(X_train,y_train)

LinearDiscriminantAnalysis()

In [55]:
predictions_lda = lda_model.predict(X_test)

In [56]:
accuracy = accuracy_score(y_test, predictions_lda)
precision = precision_score(y_test, predictions_lda)
recall = recall_score(y_test, predictions_lda)
f1 = f1_score(y_test, predictions_lda)

In [57]:
print(f"Accuracy: {accuracy * 100:.2f}%")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")

Accuracy: 91.71%
Precision: 0.93
Recall: 0.99
F1 Score: 0.96


## KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn_classifier = KNeighborsClassifier(n_neighbors=5)
knn_classifier.fit(X_train, y_train)
knn_pred = knn_classifier.predict(X_test)

accuracy = accuracy_score(y_test, knn_pred)
precision = precision_score(y_test, knn_pred)
recall = recall_score(y_test, knn_pred)
f1 = f1_score(y_test, knn_pred)

print(f"Accuracy: {accuracy * 100:.2f}%")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")


## Naive Bayes

In [ ]:
from sklearn.naive_bayes import MultinomialNB
nb_classifier = MultinomialNB()
nb_classifier.fit(X_train, y_train)
nb_pred = nb_classifier.predict(X_test)

accuracy = accuracy_score(y_test, nb_pred)
precision = precision_score(y_test, nb_pred)
recall = recall_score(y_test, nb_pred)
f1 = f1_score(y_test, nb_pred)

print(f"Accuracy: {accuracy * 100:.2f}%")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")



## XG-Boost

In [ ]:
y_train_mapped = np.where(y_train == -1, 0, y_train)
y_test_mapped = np.where(y_test == -1, 0, y_test)
xgb_classifier = xgb.XGBClassifier()
xgb_classifier.fit(X_train, y_train_mapped)
xgb_pred = xgb_classifier.predict(X_test)

accuracy = accuracy_score(y_test_mapped, xgb_pred)
precision = precision_score(y_test_mapped, xgb_pred)
recall = recall_score(y_test_mapped, xgb_pred)
f1 = f1_score(y_test_mapped, xgb_pred)

print(f"Accuracy: {accuracy * 100:.2f}%")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")
