# Eclipse Platform Bugg Classification:

In [2]:
## Importing some basic required libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [4]:
ep_data1 = pd.read_csv("D:\External_Projects\Kaushiki_Mishra\Data and Code\eclipse_platform.csv")

In [5]:
ep_data1

Issue_id Priority Component  Duplicated_issue  \
0             1       P3      Team               NaN   
1             2       P5      Team               NaN   
2             3       P5      Team               NaN   
3             4       P5      Team               NaN   
4             5       P3      Team               NaN   
...         ...      ...       ...               ...   
85151    424679       P3       IDE          390071.0   
85152    424714       P3        UI               NaN   
85153    424722       P3   Website               NaN   
85154    424764       P3       SWT               NaN   
85155    424767       P3       IDE               NaN   

                                                   Title  \
0        Usability issue with external editors (1GE6IRL)   
1      Opening repository resources doesnt honor type...   
2              Sync does not indicate deletion (1GIEN83)   
3      need better error message if catching up over ...   
4      ISharingManager sharing API inconsistent (1GAU...   
...                                                  ...   
85151                                 Crash on bootstarp   
85152                [GTK/Linux] Blank Windows with GTK3   
85153                                           software   
85154                            Crash (MacOS) - getIvar   
85155                                            eclipse   

                                             Description    Status  \
0      - Setup a project that contains a *.gif resour...    CLOSED   
1      Opening repository resource always open the de...  RESOLVED   
2      KM (10/2/2001 5:55:18 PM); \tThis PR about the...  RESOLVED   
3      - become synchronized with some project in a r...  RESOLVED   
4      For getting/setting the managed state of a res...  RESOLVED   
...                                                  ...       ...   
85151                                                NaN    CLOSED   
85152  I started testing 4.4 and noticed the editor w...    CLOSED   
85153                                                NaN  RESOLVED   
85154  Process:         eclipse [42412]; Path:       ...    CLOSED   
85155                                                NaN    CLOSED   

       Resolution Version               Created_time  \
0           FIXED     2.0  2001-10-10 21:34:00 -0400   
1           FIXED     2.0  2001-10-10 21:34:00 -0400   
2           FIXED     2.0  2001-10-10 21:34:00 -0400   
3           FIXED     2.0  2001-10-10 21:34:00 -0400   
4         WONTFIX     2.0  2001-10-10 21:34:00 -0400   
...           ...     ...                        ...   
85151   DUPLICATE     4.3  2013-12-26 20:12:00 -0500   
85152  NDUPLICATE     4.4  2013-12-28 08:57:00 -0500   
85153     INVALID   4.3.1  2013-12-29 03:57:00 -0500   
85154  NDUPLICATE     4.4  2013-12-30 16:43:00 -0500   
85155     INVALID   3.2.2  2013-12-30 18:05:00 -0500   

                   Resolved_time  
0      2012-02-09 15:57:47 -0500  
1      2002-05-07 10:33:56 -0400  
2      2010-05-07 10:28:53 -0400  
3      2002-03-01 16:27:31 -0500  
4      2008-08-15 08:04:36 -0400  
...                          ...  
85151  2013-12-31 05:32:07 -0500  
85152  2014-01-04 13:54:33 -0500  
85153  2014-01-07 08:47:24 -0500  
85154  2013-12-31 04:35:42 -0500  
85155  2013-12-31 04:21:29 -0500  

[85156 rows x 11 columns]

In [6]:
ep_data1.shape

(85156, 11)

In [7]:
ep_data1.isna().sum()

Issue_id                0
Priority                0
Component               0
Duplicated_issue    70752
Title                   0
Description           129
Status                  0
Resolution              0
Version                 0
Created_time            0
Resolved_time           0
dtype: int64

In [8]:
ep_data2 = ep_data1.drop(columns=["Duplicated_issue"])

In [9]:
ep_data2.shape

(85156, 10)

In [10]:
ep_data2.isna().sum()

Issue_id           0
Priority           0
Component          0
Title              0
Description      129
Status             0
Resolution         0
Version            0
Created_time       0
Resolved_time      0
dtype: int64

In [11]:
ep_data3 = ep_data2.dropna()

In [12]:
ep_data3.isna().sum()

Issue_id         0
Priority         0
Component        0
Title            0
Description      0
Status           0
Resolution       0
Version          0
Created_time     0
Resolved_time    0
dtype: int64

In [13]:
ep_data3.shape

(85027, 10)

In [14]:
ep_data4 = ep_data3.reset_index(drop=True)

In [15]:
ep_data4

Issue_id Priority Component  \
0             1       P3      Team   
1             2       P5      Team   
2             3       P5      Team   
3             4       P5      Team   
4             5       P3      Team   
...         ...      ...       ...   
85022    424658       P3       SWT   
85023    424671       P3       IDE   
85024    424672       P3        UI   
85025    424714       P3        UI   
85026    424764       P3       SWT   

                                                   Title  \
0        Usability issue with external editors (1GE6IRL)   
1      Opening repository resources doesnt honor type...   
2              Sync does not indicate deletion (1GIEN83)   
3      need better error message if catching up over ...   
4      ISharingManager sharing API inconsistent (1GAU...   
...                                                  ...   
85022  Eclipse Kepler Often Crash On Ubuntu 13.04 and...   
85023                         Eclipse crashes on startup   
85024                          Menu Bar does not display   
85025                [GTK/Linux] Blank Windows with GTK3   
85026                            Crash (MacOS) - getIvar   

                                             Description    Status  \
0      - Setup a project that contains a *.gif resour...    CLOSED   
1      Opening repository resource always open the de...  RESOLVED   
2      KM (10/2/2001 5:55:18 PM); \tThis PR about the...  RESOLVED   
3      - become synchronized with some project in a r...  RESOLVED   
4      For getting/setting the managed state of a res...  RESOLVED   
...                                                  ...       ...   
85022  Eclipse Kepler often crash on ubuntu 13.04 and...  RESOLVED   
85023  Created attachment 238574; /workspace/.metadat...    CLOSED   
85024  when i click on one of the buttons on the menu...    CLOSED   
85025  I started testing 4.4 and noticed the editor w...    CLOSED   
85026  Process:         eclipse [42412]; Path:       ...    CLOSED   

       Resolution Version               Created_time  \
0           FIXED     2.0  2001-10-10 21:34:00 -0400   
1           FIXED     2.0  2001-10-10 21:34:00 -0400   
2           FIXED     2.0  2001-10-10 21:34:00 -0400   
3           FIXED     2.0  2001-10-10 21:34:00 -0400   
4         WONTFIX     2.0  2001-10-10 21:34:00 -0400   
...           ...     ...                        ...   
85022  NDUPLICATE   4.3.1  2013-12-26 04:06:00 -0500   
85023   DUPLICATE     4.4  2013-12-26 12:22:00 -0500   
85024  NDUPLICATE     4.3  2013-12-26 12:32:00 -0500   
85025  NDUPLICATE     4.4  2013-12-28 08:57:00 -0500   
85026  NDUPLICATE     4.4  2013-12-30 16:43:00 -0500   

                   Resolved_time  
0      2012-02-09 15:57:47 -0500  
1      2002-05-07 10:33:56 -0400  
2      2010-05-07 10:28:53 -0400  
3      2002-03-01 16:27:31 -0500  
4      2008-08-15 08:04:36 -0400  
...                          ...  
85022  2014-01-03 21:42:20 -0500  
85023  2013-12-31 05:54:48 -0500  
85024  2014-01-27 09:20:08 -0500  
85025  2014-01-04 13:54:33 -0500  
85026  2013-12-31 04:35:42 -0500  

[85027 rows x 10 columns]

In [16]:
ep_data4.columns

Index(['Issue_id', 'Priority', 'Component', 'Title', 'Description', 'Status',
       'Resolution', 'Version', 'Created_time', 'Resolved_time'],
      dtype='object')

In [17]:
ep_data5 = ep_data4.drop(columns=["Issue_id","Created_time", "Resolved_time"])

In [18]:
ep_data5

Priority Component                                              Title  \
0           P3      Team    Usability issue with external editors (1GE6IRL)   
1           P5      Team  Opening repository resources doesnt honor type...   
2           P5      Team          Sync does not indicate deletion (1GIEN83)   
3           P5      Team  need better error message if catching up over ...   
4           P3      Team  ISharingManager sharing API inconsistent (1GAU...   
...        ...       ...                                                ...   
85022       P3       SWT  Eclipse Kepler Often Crash On Ubuntu 13.04 and...   
85023       P3       IDE                         Eclipse crashes on startup   
85024       P3        UI                          Menu Bar does not display   
85025       P3        UI                [GTK/Linux] Blank Windows with GTK3   
85026       P3       SWT                            Crash (MacOS) - getIvar   

                                             Description    Status  \
0      - Setup a project that contains a *.gif resour...    CLOSED   
1      Opening repository resource always open the de...  RESOLVED   
2      KM (10/2/2001 5:55:18 PM); \tThis PR about the...  RESOLVED   
3      - become synchronized with some project in a r...  RESOLVED   
4      For getting/setting the managed state of a res...  RESOLVED   
...                                                  ...       ...   
85022  Eclipse Kepler often crash on ubuntu 13.04 and...  RESOLVED   
85023  Created attachment 238574; /workspace/.metadat...    CLOSED   
85024  when i click on one of the buttons on the menu...    CLOSED   
85025  I started testing 4.4 and noticed the editor w...    CLOSED   
85026  Process:         eclipse [42412]; Path:       ...    CLOSED   

       Resolution Version  
0           FIXED     2.0  
1           FIXED     2.0  
2           FIXED     2.0  
3           FIXED     2.0  
4         WONTFIX     2.0  
...           ...     ...  
85022  NDUPLICATE   4.3.1  
85023   DUPLICATE     4.4  
85024  NDUPLICATE     4.3  
85025  NDUPLICATE     4.4  
85026  NDUPLICATE     4.4  

[85027 rows x 7 columns]

In [19]:
ep_data5["Resolution"].value_counts()

Resolution
FIXED          42327
DUPLICATE      14398
WONTFIX         9666
WORKSFORME      8414
INVALID         7090
NDUPLICATE      2330
NOT_ECLIPSE      801
MOVED              1
Name: count, dtype: int64

In [20]:
ep_data5["Resolution"] = [-1 if bug_type == "INVALID" else 1 for bug_type in ep_data5["Resolution"]]

In [21]:
ep_data5["Resolution"].value_counts()      ## It is highly imbalanced dataset

Resolution
 1    77937
-1     7090
Name: count, dtype: int64

In [22]:
X = ep_data5.drop(columns = "Resolution")  ## Our input features for futher analysis

In [23]:
X

Priority Component                                              Title  \
0           P3      Team    Usability issue with external editors (1GE6IRL)   
1           P5      Team  Opening repository resources doesnt honor type...   
2           P5      Team          Sync does not indicate deletion (1GIEN83)   
3           P5      Team  need better error message if catching up over ...   
4           P3      Team  ISharingManager sharing API inconsistent (1GAU...   
...        ...       ...                                                ...   
85022       P3       SWT  Eclipse Kepler Often Crash On Ubuntu 13.04 and...   
85023       P3       IDE                         Eclipse crashes on startup   
85024       P3        UI                          Menu Bar does not display   
85025       P3        UI                [GTK/Linux] Blank Windows with GTK3   
85026       P3       SWT                            Crash (MacOS) - getIvar   

                                             Description    Status Version  
0      - Setup a project that contains a *.gif resour...    CLOSED     2.0  
1      Opening repository resource always open the de...  RESOLVED     2.0  
2      KM (10/2/2001 5:55:18 PM); \tThis PR about the...  RESOLVED     2.0  
3      - become synchronized with some project in a r...  RESOLVED     2.0  
4      For getting/setting the managed state of a res...  RESOLVED     2.0  
...                                                  ...       ...     ...  
85022  Eclipse Kepler often crash on ubuntu 13.04 and...  RESOLVED   4.3.1  
85023  Created attachment 238574; /workspace/.metadat...    CLOSED     4.4  
85024  when i click on one of the buttons on the menu...    CLOSED     4.3  
85025  I started testing 4.4 and noticed the editor w...    CLOSED     4.4  
85026  Process:         eclipse [42412]; Path:       ...    CLOSED     4.4  

[85027 rows x 6 columns]

In [24]:
Bug_details = []
for i in range(len(X)):
  Bug_detail = ' '.join(detail for detail in X.iloc[i,0:6])
  Bug_details.append(Bug_detail)

In [25]:
Bug_details[2]

'P5 Team Sync does not indicate deletion (1GIEN83) KM (10/2/2001 5:55:18 PM); \tThis PR about the deletion indicator in the sync viewer being too subtle.; \tThis would be even more true for someone with vision problems.; \tNE has good suggestion of using the label of the compare text viewer.; \tWe may also consider a better icon.; \tOn to the PR....; ; - delete file from project; - synchronize; - there is no indication that the file has been deleted from the workspace; - it looks the same as if the file is in the workspace but is empty; ; NOTES:; ; KM (8/15/2001 3:37:53 PM); \tIt should appear as a rightfacing - arrow in the sync view.; \tSent screen cap to NE requesting clarification.; ; NE (8/20/01 9:13:38 AM); \tThe - in the arrow is clearer when there are other arrows present too (the + and change ones).; \tOtherwise; its easy to miss the distinction; especially when the users attention is focussed; \ton the text compare panes.; \tId expect the Workspace file: label to indicate tha

In [26]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [27]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\amanv\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [28]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\amanv\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [29]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\amanv\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [30]:
Lemmatizer = WordNetLemmatizer()

In [30]:
bug_details_cleaned = []

for i in range(len(Bug_details)):
  bug_detail = Bug_details[i]
  bug_detail = re.sub(r'\(\d{1,2}/\d{1,2}/\d{4} \d{1,2}:\d{1,2}:\d{1,2} [APMapm]{2}\);', '', bug_detail)
  bug_detail_words = nltk.word_tokenize(bug_detail)
  bug_detail_words = [Lemmatizer.lemmatize(word) for word in bug_detail_words if word not in set(stopwords.words('english'))]
  bug_detail = ' '.join(bug_detail_words)
  bug_detail = bug_detail.lower()
  bug_details_cleaned.append(bug_detail)

In [31]:
bug_details_cleaned[0]

'p3 team usability issue external editor ( 1ge6irl ) - setup project contains * .gif resource ; - release project cvs ; - edit * .gif resource external editor ; e.g . paintshop ; - save close external editor ; - navigator open icon resource verify change ; - release project ; - > nothing release ! ; - navigator open icon resource verify change still ; ; problem : i never refreshed local ; workspace hasnt changed release didnt find anything . ; however opening resource external editor found modified file disk showed change . ; ; the real problem occurs release actually find something release dont spot resource missing . ; this extremely error prone : one change didnt made build 110 ! ; ; notes : ; eg ( 5/23/01 3:00:33 pm ) ; release refresh local release . ; moving vcm ; ; ; km ( 05/27/01 5:10:19 pm ) ; comments jm related email : ; ; should free . could setting made optoinal nt mandatory . default setting could . ; consider swt team keep workspace network drive . this slow . ; ; side e

In [32]:
word_count = [len(bug_detail) for bug_detail in bug_details_cleaned]

In [33]:
ep_des_df = pd.DataFrame({
                            "Description" : bug_details_cleaned,
                            "Description_length" : word_count


})

In [34]:
ep_des_df

Description  Description_length
0      p3 team usability issue external editor ( 1ge6...                1491
1      p5 team opening repository resource doesnt hon...                 857
2      p5 team sync indicate deletion ( 1gien83 ) km ...                 788
3      p5 team need better error message catching rea...                 615
4      p3 team isharingmanager sharing api inconsiste...                 483
...                                                  ...                 ...
85022  p3 swt eclipse kepler often crash on ubuntu 13...                 155
85023  p3 ide eclipse crash startup created attachmen...                 621
85024  p3 ui menu bar display click one button menu b...                 207
85025  p3 ui [ gtk/linux ] blank windows gtk3 i start...                 397
85026  p3 swt crash ( macos ) - getivar process : ecl...               13661

[85027 rows x 2 columns]

In [35]:
ep_des_df["Description_length"].describe

<bound method NDFrame.describe of 0         1491
1          857
2          788
3          615
4          483
         ...  
85022      155
85023      621
85024      207
85025      397
85026    13661
Name: Description_length, Length: 85027, dtype: int64>

In [36]:
ep_des_df

Description  Description_length
0      p3 team usability issue external editor ( 1ge6...                1491
1      p5 team opening repository resource doesnt hon...                 857
2      p5 team sync indicate deletion ( 1gien83 ) km ...                 788
3      p5 team need better error message catching rea...                 615
4      p3 team isharingmanager sharing api inconsiste...                 483
...                                                  ...                 ...
85022  p3 swt eclipse kepler often crash on ubuntu 13...                 155
85023  p3 ide eclipse crash startup created attachmen...                 621
85024  p3 ui menu bar display click one button menu b...                 207
85025  p3 ui [ gtk/linux ] blank windows gtk3 i start...                 397
85026  p3 swt crash ( macos ) - getivar process : ecl...               13661

[85027 rows x 2 columns]

In [37]:
import tensorflow as tf

In [38]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [39]:
voc_size = 10000
one_hot_representation = [one_hot(news,voc_size) for news in bug_details_cleaned]

In [40]:
sentence_length = 10000
embedded_doc = pad_sequences(one_hot_representation,padding='pre',maxlen=sentence_length)
print(embedded_doc)

[[   0    0    0 ... 1451 6223 5745]
 [   0    0    0 ... 8406 6223 5745]
 [   0    0    0 ... 8406 6223 5745]
 ...
 [   0    0    0 ... 1451 9433 1434]
 [   0    0    0 ... 1451 9433 9433]
 [   0    0    0 ... 1451 9433 9433]]


In [41]:
X = np.array(embedded_doc)
y = np.array(ep_data5["Resolution"])

In [42]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=42)

## Support Vector Classifier

In [43]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [44]:
svm_model = SVC(kernel='rbf')
svm_model.fit(X_train, y_train)

In [ ]:
predictions_rbf = svm_model.predict(X_test)

In [ ]:
accuracy = accuracy_score(y_test, predictions_rbf)
precision = precision_score(y_test, predictions_rbf)
recall = recall_score(y_test, predictions_rbf)
f1 = f1_score(y_test, predictions_rbf)

In [ ]:

print(f"Accuracy: {accuracy * 100:.2f}%")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")

Linear Discriminant Analysis

In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [ ]:
lda_model = LinearDiscriminantAnalysis()

In [ ]:
lda_model.fit(X_train, y_train)

In [ ]:
predictions_lda = lda_model.predict(X_test)

In [ ]:
accuracy = accuracy_score(y_test, predictions_lda)
precision = precision_score(y_test, predictions_lda)
recall = recall_score(y_test, predictions_lda)
f1 = f1_score(y_test, predictions_lda)

In [ ]:
print(f"Accuracy: {accuracy * 100:.2f}%")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")

## KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn_classifier = KNeighborsClassifier(n_neighbors=5)
knn_classifier.fit(X_train, y_train)
knn_pred = knn_classifier.predict(X_test)

accuracy = accuracy_score(y_test, knn_pred)
precision = precision_score(y_test, knn_pred)
recall = recall_score(y_test, knn_pred)
f1 = f1_score(y_test, knn_pred)

print(f"Accuracy: {accuracy * 100:.2f}%")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")


## Naive Bayes

In [ ]:
from sklearn.naive_bayes import MultinomialNB
nb_classifier = MultinomialNB()
nb_classifier.fit(X_train, y_train)
nb_pred = nb_classifier.predict(X_test)

accuracy = accuracy_score(y_test, nb_pred)
precision = precision_score(y_test, nb_pred)
recall = recall_score(y_test, nb_pred)
f1 = f1_score(y_test, nb_pred)

print(f"Accuracy: {accuracy * 100:.2f}%")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")



## XG- Boost

In [ ]:
y_train_mapped = np.where(y_train == -1, 0, y_train)
y_test_mapped = np.where(y_test == -1, 0, y_test)
xgb_classifier = xgb.XGBClassifier()
xgb_classifier.fit(X_train, y_train_mapped)
xgb_pred = xgb_classifier.predict(X_test)

accuracy = accuracy_score(y_test_mapped, xgb_pred)
precision = precision_score(y_test_mapped, xgb_pred)
recall = recall_score(y_test_mapped, xgb_pred)
f1 = f1_score(y_test_mapped, xgb_pred)

print(f"Accuracy: {accuracy * 100:.2f}%")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")
