# OpenOffice Fields Bug Classifier


In [1]:
## Importing some basic required libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
mf_data1 = pd.read_csv("D:\External_Projects\Kaushiki_Mishra\Data and Code\OpenOfficeFields.csv")

In [3]:
mf_data1

BugID  MasterID  MergeID  Product    Component     Type Priority  \
0      84934         0        0     Calc  programming  trivial       P3   
1      94985         0        0       qa          www  trivial       P3   
2      94986         0        0       qa  testscripts  trivial       P3   
3      94987         0        0   Writer         code  trivial       P3   
4      94988         0        0  General         code  trivial       P3   
...      ...       ...      ...      ...          ...      ...      ...   
31130  94983         0        0     Calc           ui  trivial       P3   
31131  94984         0        0  App Dev          api  trivial       P3   
31132  85939         0        0  General           ui  trivial       P4   
31133  85036         0        0  App Dev    scripting  trivial       P3   
31134  84943         0        0   Writer           ui  trivial       P3   

       PriorityNumber        Version  VersionNumber  ...  \
0                 3.0      OOo 2.3.1            0.0  ...   
1                 3.0        current            0.0  ...   
2                 3.0        current            0.0  ...   
3                 3.0       OOO300m9            0.0  ...   
4                 3.0       OOO300m9            0.0  ...   
...               ...            ...            ...  ...   
31130             3.0        OOo 3.0            0.0  ...   
31131             3.0  pre AOO 3.4.0            0.0  ...   
31132             4.0      OOo 2.3.1            0.0  ...   
31133             3.0  pre AOO 3.4.0            0.0  ...   
31134             3.0      OOo 2.3.1            0.0  ...   

                           CloseDate          Status Stars   crypto   general  \
0      Fri Oct 17 13:52:32 IRST 2008           FIXED     0  4.49804   6.27436   
1      Tue Jul 21 18:59:33 IRDT 2009           FIXED     0  8.03226   8.03226   
2      Tue Dec 16 18:14:33 IRST 2008           FIXED     0  0.00000   0.00000   
3      Mon Feb 09 14:00:30 IRST 2009           FIXED     0  5.34247   5.64565   
4      Mon Jan 19 19:00:12 IRST 2009  IRREPRODUCIBLE     0  0.52058   3.12153   
...                              ...             ...   ...      ...       ...   
31130  Fri Mar 15 13:10:18 IRST 2013  IRREPRODUCIBLE     0  3.27015   7.00472   
31131  Mon Feb 25 00:40:17 IRST 2013           FIXED     0  3.09946   4.31044   
31132  Mon Mar 15 17:08:25 IRST 2010  IRREPRODUCIBLE     0  5.79982  10.76450   
31133  Mon Feb 25 00:30:32 IRST 2013           FIXED     0  8.11245   5.79051   
31134  Fri Feb 08 01:27:32 IRST 2013             NaN     0  9.02306  11.54245   

          java  networking                                              Title  \
0      4.89773     4.89773                           odff: days360 compliance   
1      5.76255     6.80746             distribute norwegian 3.0.0rc4 as final   
2      0.00000     0.00000                       ssh-file for cws/svm-tooling   
3      5.34247     5.64565  api service annotation change incompatible wit...   
4      0.52058     0.52058                      pdf import installation fails   
...        ...         ...                                                ...   
31130  5.48095     5.48095                     scrollwheel opposite direction   
31131  6.14400     4.31044  runner: checkapi should use environment variab...   
31132  7.30592     7.68534                       australian spell check issue   
31133  8.11245     5.79051             vba: strconv function is not supported   
31134  9.91670    10.70828  cannot proceed in mail merge at insert address...   

                                             Description Summary  
0      mail reader message refers: http://www.openoff...     NaN  
1      i got the following approval  > -------- origi...     NaN  
2                           ssh-file for cws/svm-tooling     NaN  
3      an existing macro that created text notes did ...     NaN  
4      while trying to install the pdf import extensi...     NaN  
...                                  

In [4]:
mf_data1.shape

(31135, 21)

In [5]:
mf_data1.isna().sum()

BugID                 0
MasterID              0
MergeID               0
Product               3
Component             3
Type                  3
Priority              3
PriorityNumber        0
Version               3
VersionNumber         0
OpenDate              0
CloseDate             0
Status             9128
Stars                 0
crypto                0
general               0
java                  0
networking            0
Title                 3
Description           4
Summary           31135
dtype: int64

In [6]:
mf_data2 = mf_data1.drop(columns="Summary")

In [7]:
mf_data2["Status"].value_counts()

Status
FIXED             11258
DUPLICATE          4460
IRREPRODUCIBLE     2809
INVALID            2729
WONTFIX             750
MOVED                 1
Name: count, dtype: int64

In [8]:
mf_data3 = mf_data2.dropna()

In [9]:
mf_data4 = mf_data3.reset_index(drop=True)

In [10]:
mf_data4

BugID  MasterID  MergeID  Product    Component     Type Priority  \
0      84934         0        0     Calc  programming  trivial       P3   
1      94985         0        0       qa          www  trivial       P3   
2      94986         0        0       qa  testscripts  trivial       P3   
3      94987         0        0   Writer         code  trivial       P3   
4      94988         0        0  General         code  trivial       P3   
...      ...       ...      ...      ...          ...      ...      ...   
22002  94982         0    35247   Writer   formatting  trivial       P3   
22003  94983         0        0     Calc           ui  trivial       P3   
22004  94984         0        0  App Dev          api  trivial       P3   
22005  85939         0        0  General           ui  trivial       P4   
22006  85036         0        0  App Dev    scripting  trivial       P3   

       PriorityNumber        Version  VersionNumber  \
0                 3.0      OOo 2.3.1            0.0   
1                 3.0        current            0.0   
2                 3.0        current            0.0   
3                 3.0       OOO300m9            0.0   
4                 3.0       OOO300m9            0.0   
...               ...            ...            ...   
22002             3.0        OOo 3.0            0.0   
22003             3.0        OOo 3.0            0.0   
22004             3.0  pre AOO 3.4.0            0.0   
22005             4.0      OOo 2.3.1            0.0   
22006             3.0  pre AOO 3.4.0            0.0   

                            OpenDate                      CloseDate  \
0      Wed Jan 02 04:47:00 IRST 2008  Fri Oct 17 13:52:32 IRST 2008   
1      Thu Oct 16 13:10:00 IRST 2008  Tue Jul 21 18:59:33 IRDT 2009   
2      Thu Oct 16 13:48:00 IRST 2008  Tue Dec 16 18:14:33 IRST 2008   
3      Thu Oct 16 13:48:00 IRST 2008  Mon Feb 09 14:00:30 IRST 2009   
4      Thu Oct 16 14:00:00 IRST 2008  Mon Jan 19 19:00:12 IRST 2009   
...                              ...                            ...   
22002  Thu Oct 16 12:44:00 IRST 2008  Thu Oct 16 14:55:28 IRST 2008   
22003  Thu Oct 16 12:44:00 IRST 2008  Fri Mar 15 13:10:18 IRST 2013   
22004  Thu Oct 16 12:53:00 IRST 2008  Mon Feb 25 00:40:17 IRST 2013   
22005  Thu Feb 07 16:33:00 IRST 2008  Mon Mar 15 17:08:25 IRST 2010   
22006  Mon Jan 07 08:47:00 IRST 2008  Mon Feb 25 00:30:32 IRST 2013   

               Status  Stars   crypto   general     java  networking  \
0               FIXED      0  4.49804   6.27436  4.89773     4.89773   
1               FIXED      0  8.03226   8.03226  5.76255     6.80746   
2               FIXED      0  0.00000   0.00000  0.00000     0.00000   
3               FIXED      0  5.34247   5.64565  5.34247     5.64565   
4      IRREPRODUCIBLE      0  0.52058   3.12153  0.52058     0.52058   
...               ...    ...      ...       ...      ...         ...   
22002       DUPLICATE      0  5.14948   5.14948  3.48163     5.14948   
22003  IRREPRODUCIBLE      0  3.27015   7.00472  5.48095     5.48095   
22004           FIXED      0  3.09946   4.31044  6.14400     4.31044   
22005  IRREPRODUCIBLE      0  5.79982  10.76450  7.30592     7.68534   
22006           FIXED      0  8.11245   5.79051  8.11245     5.79051   

                                                   Title  \
0                               odff: days360 compliance   
1                 distribute norwegian 3.0.0rc4 as final   
2                           ssh-file for cws/svm-tooling   
3      api service annotation change incompatible wit...   
4                          pdf import installation fails   
...                                                  ...   
22002                    ordinal numbers missing in date   
22003                     scrollwheel opposite direction   
22004  runner: checkapi should use environment variab...   
22005                       australian spell check issue   
22006             vba: strconv function is not supported   

      

In [11]:
mf_data4["Status"].value_counts()

Status
FIXED             11258
DUPLICATE          4460
IRREPRODUCIBLE     2809
INVALID            2729
WONTFIX             750
MOVED                 1
Name: count, dtype: int64

In [12]:
mf_data4["Status"] = [-1 if bug_type == "INVALID" else 1 for bug_type in mf_data4["Status"]]

In [13]:
mf_data4["Status"].value_counts()   ## The data set is highly imbalanced

Status
 1    19278
-1     2729
Name: count, dtype: int64

In [14]:
mf_data5 = mf_data4.drop(columns = ["BugID","MasterID","MergeID","OpenDate","CloseDate","Stars","VersionNumber"])

In [15]:
mf_data5

Product    Component     Type Priority  PriorityNumber        Version  \
0         Calc  programming  trivial       P3             3.0      OOo 2.3.1   
1           qa          www  trivial       P3             3.0        current   
2           qa  testscripts  trivial       P3             3.0        current   
3       Writer         code  trivial       P3             3.0       OOO300m9   
4      General         code  trivial       P3             3.0       OOO300m9   
...        ...          ...      ...      ...             ...            ...   
22002   Writer   formatting  trivial       P3             3.0        OOo 3.0   
22003     Calc           ui  trivial       P3             3.0        OOo 3.0   
22004  App Dev          api  trivial       P3             3.0  pre AOO 3.4.0   
22005  General           ui  trivial       P4             4.0      OOo 2.3.1   
22006  App Dev    scripting  trivial       P3             3.0  pre AOO 3.4.0   

       Status   crypto   general     java  networking  \
0           1  4.49804   6.27436  4.89773     4.89773   
1           1  8.03226   8.03226  5.76255     6.80746   
2           1  0.00000   0.00000  0.00000     0.00000   
3           1  5.34247   5.64565  5.34247     5.64565   
4           1  0.52058   3.12153  0.52058     0.52058   
...       ...      ...       ...      ...         ...   
22002       1  5.14948   5.14948  3.48163     5.14948   
22003       1  3.27015   7.00472  5.48095     5.48095   
22004       1  3.09946   4.31044  6.14400     4.31044   
22005       1  5.79982  10.76450  7.30592     7.68534   
22006       1  8.11245   5.79051  8.11245     5.79051   

                                                   Title  \
0                               odff: days360 compliance   
1                 distribute norwegian 3.0.0rc4 as final   
2                           ssh-file for cws/svm-tooling   
3      api service annotation change incompatible wit...   
4                          pdf import installation fails   
...                                                  ...   
22002                    ordinal numbers missing in date   
22003                     scrollwheel opposite direction   
22004  runner: checkapi should use environment variab...   
22005                       australian spell check issue   
22006             vba: strconv function is not supported   

                                             Description  
0      mail reader message refers: http://www.openoff...  
1      i got the following approval  > -------- origi...  
2                           ssh-file for cws/svm-tooling  
3      an existing macro that created text notes did ...  
4      while trying to install the pdf import extensi...  
...                                                  ...  
22002  when inserting a date field the number formatt...  
22003  when i use the scrollwheel to scroll vertical ...  
22004  if you develop the runner and you need to chec...  
22005  dear community   after one installs openoffice...  
22006  in vba  the strconv function returns a string ...  

[22007 rows x 13 columns]

In [16]:
X = mf_data5.drop(columns = "Status")

In [17]:
Bug_details = []
for i in range(len(X)):
  Bug_detail = ' '.join(str(detail) for detail in X.iloc[i,0:12])
  Bug_details.append(Bug_detail)

In [18]:
Bug_details[3]

'Writer code trivial P3 3.0 OOO300m9 5.34247 5.64565 5.34247 5.64565 api service annotation change incompatible with old code an existing macro that created text notes did not work on ooo 3.0.  dim mynote as object dim unedate as new com.sun.star.util.date mynote = thiscomponent.createinstance("com.sun.star.text.textfield.annotation") mynote.author = "somebody"  mynote.content = "this is the text of the note" unedate.day = 15 unedate.month = 7 unedate.year  = 2008 mynote.date = unedate \' <<< -- property not found mytext.inserttextcontent(mycursor  mynote  false)   investigation shows two problems:  1 - service com.sun.star.text.textfield.annotation provides a note object with a  property "datetimevalue" instead of property "date". the new one has the same structure as the old property : com.sun.star.util.date the idl documentation of the service has not changed : the property date is  described  not the property datetimevalue.   changing a name of a property is unacceptable as it brea

In [19]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [20]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\amanv\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [21]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\amanv\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [22]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\amanv\AppData\Roaming\nltk_data...


[nltk_data]   Package wordnet is already up-to-date!


True

In [23]:
Lemmatizer = WordNetLemmatizer()

In [24]:
bug_details_cleaned = []

for i in range(len(Bug_details)):
    bug_detail = Bug_details[i]
    bug_detail = re.sub(r'\(\d{1,2}/\d{1,2}/\d{4} \d{1,2}:\d{1,2}:\d{1,2} [APMapm]{2}\);', '', bug_detail)
    bug_detail_words = nltk.word_tokenize(bug_detail)
    bug_detail_words = [Lemmatizer.lemmatize(word) for word in bug_detail_words if word not in set(stopwords.words('english'))]
    bug_detail = ' '.join(bug_detail_words)
    bug_detail = bug_detail.lower()
    bug_details_cleaned.append(bug_detail)

In [25]:
word_count = [len(bug_detail) for bug_detail in bug_details_cleaned]

In [26]:
ep_des_df = pd.DataFrame({
                            "Description" : bug_details_cleaned,
                            "Description_length" : word_count


})

In [27]:
ep_des_df["Description_length"].describe()

count     22007.000000
mean        696.950516
std        4167.831994
min          52.000000
25%         249.000000
50%         367.000000
75%         567.000000
max      393408.000000
Name: Description_length, dtype: float64

In [28]:
import tensorflow as tf

In [29]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [30]:
voc_size = 10000
one_hot_representation = [one_hot(news,voc_size) for news in bug_details_cleaned]

In [31]:
sentence_length = 700
embedded_doc = pad_sequences(one_hot_representation,padding='pre',maxlen=sentence_length)
print(embedded_doc)

[[   0    0    0 ... 9455 3684 7755]
 [   0    0    0 ...  106 1770  106]
 [   0    0    0 ... 7860 5168 5078]
 ...
 [   0    0    0 ... 8991 9364 1532]
 [   0    0    0 ... 2851 6120 7358]
 [   0    0    0 ... 7343   30  846]]


In [32]:
X = np.array(embedded_doc)
y = np.array(mf_data5["Status"])

In [33]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=42)

# SVC

In [34]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [ ]:
svm_model = SVC(kernel='rbf')
svm_model.fit(X_train, y_train)

In [ ]:
predictions_rbf = svm_model.predict(X_test)


In [37]:
accuracy = accuracy_score(y_test, predictions_rbf)
precision = precision_score(y_test, predictions_rbf)
recall = recall_score(y_test, predictions_rbf)
f1 = f1_score(y_test, predictions_rbf)


In [38]:

print(f"Accuracy: {accuracy * 100:.2f}%")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")

Accuracy: 86.61%
Precision: 0.87
Recall: 1.00
F1 Score: 0.93


# LDA

In [40]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [41]:
lda_model = LinearDiscriminantAnalysis()

In [42]:
lda_model.fit(X_train, y_train)

LinearDiscriminantAnalysis()

In [43]:
predictions_lda = lda_model.predict(X_test)

In [44]:
accuracy = accuracy_score(y_test, predictions_lda)
precision = precision_score(y_test, predictions_lda)
recall = recall_score(y_test, predictions_lda)
f1 = f1_score(y_test, predictions_lda)

In [45]:
print(f"Accuracy: {accuracy * 100:.2f}%")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")

Accuracy: 85.36%
Precision: 0.87
Recall: 0.98
F1 Score: 0.92


## KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn_classifier = KNeighborsClassifier(n_neighbors=5)
knn_classifier.fit(X_train, y_train)
knn_pred = knn_classifier.predict(X_test)

accuracy = accuracy_score(y_test, knn_pred)
precision = precision_score(y_test, knn_pred)
recall = recall_score(y_test, knn_pred)
f1 = f1_score(y_test, knn_pred)

print(f"Accuracy: {accuracy * 100:.2f}%")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")


## Naive BAyes

In [ ]:
from sklearn.naive_bayes import MultinomialNB
nb_classifier = MultinomialNB()
nb_classifier.fit(X_train, y_train)
nb_pred = nb_classifier.predict(X_test)

accuracy = accuracy_score(y_test, nb_pred)
precision = precision_score(y_test, nb_pred)
recall = recall_score(y_test, nb_pred)
f1 = f1_score(y_test, nb_pred)

print(f"Accuracy: {accuracy * 100:.2f}%")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")



## XG-Boost

In [ ]:
y_train_mapped = np.where(y_train == -1, 0, y_train)
y_test_mapped = np.where(y_test == -1, 0, y_test)
xgb_classifier = xgb.XGBClassifier()
xgb_classifier.fit(X_train, y_train_mapped)
xgb_pred = xgb_classifier.predict(X_test)

accuracy = accuracy_score(y_test_mapped, xgb_pred)
precision = precision_score(y_test_mapped, xgb_pred)
recall = recall_score(y_test_mapped, xgb_pred)
f1 = f1_score(y_test_mapped, xgb_pred)

print(f"Accuracy: {accuracy * 100:.2f}%")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")
